### ISSUE TITLE
ConfigEntry attribute error

### ISSUE THREAD

**Issue by bradkeifer** [bradkeifer/home-assistant-custom-components#1]
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/hal/__init__.py", line 137, in async_setup_entry
    f"entry.domain {entry.domain}, "
AttributeError: 'ConfigEntry' object has no attribute 'connection_class'

**Comment by bradkeifer** [comment]
Fixed. __init__.py and manifest.json modified.
